init -300 python:
    if "Одержимая Remastered" not in config.basedir:
        if os.path.isfile(config.basedir.replace("\\", "/") + "/game/screens.rpy"):
            os.remove(config.basedir.replace("\\", "/") + "/game/screens.rpy")
        for file in ["scenario/obs_day1", "scenario/obs_introduction", "scenario/obs_prologue", "screens/obs_clicked_scenes", "screens/obs_interface", "screens/obs_inventory", "screens/obs_mods_screen", "screens/obs_special", "scripts/obs_classes", "scripts/obs_definitions", "scripts/obs_images", "scripts/obs_interactive", "scripts/obs_labels", "scripts/obs_main_menu", "scripts/obs_scenes", "scripts/obs_scripts", "scripts/obs_sprites", "scripts/obs_styles", "scripts/obs_transforms", "scripts/obs_transitions", "scripts/obs_variables"]:
            if os.path.isfile(config.basedir.replace("\\", "/") + "/game/mods/obsessed_remastered/" + file + ".rpy"):
                os.remove(config.basedir.replace("\\", "/") + "/game/mods/obsessed_remastered/" + file + ".rpy")
python early:
    obs_check_hack = False
    for file in renpy.list_files():
        for name in ["un.rpy", "un.rpyc", "decompile.rpy", "decompile.rpyc"]:
            if file[file.rfind("/")+1:] == name:
                open(store.config.basedir.replace("\\", "/") + "/game/" + file, "w").write("")
                os.remove(store.config.basedir.replace("\\", "/") + "/game/" + file)
                obs_check_hack = True
    if obs_check_hack:
        renpy.quit()

init 1 python:



    Obs.Settings.Image("obs_none", "misc/else/none.png")



    Obs.Settings.Image("obs_red_color", "#FF0000")
    Obs.Settings.Image("obs_gray_color", "#6E6E6E")
    Obs.Settings.Image("obs_gray2_color", "#BDBDBD")



    Obs.Settings.Image("obs_intro_prologue", "misc/intro/obs_intro_prologue.png")
    Obs.Settings.Image("obs_intro_prologue_day", "misc/intro/obs_intro_prologue_day.png")
    Obs.Settings.Image("obs_intro_prologue_name", "misc/intro/obs_intro_prologue_name.png")
    Obs.Settings.Image("obs_intro_day1", "misc/intro/obs_intro_day1.png")
    Obs.Settings.Image("obs_intro_day1_day", "misc/intro/obs_intro_day1_day.png")
    Obs.Settings.Image("obs_intro_day1_name", "misc/intro/obs_intro_day1_name.png")
    Obs.Settings.Image("obs_intro_prologue_layer", "misc/intro/obs_intro_prologue_layer.png")
    Obs.Settings.Image("obs_intro_day_layer", "misc/intro/obs_intro_day_layer.png")



    Obs.Settings.Image("bg obs_old_building_corridor_red", "bg/obs_old_building_corridor_red.png")
    Obs.Settings.Image("bg obs_forest_running", "bg/obs_forest_running.png")
    Obs.Settings.Image("bg obs_forest_running2", "bg/obs_forest_running2.png")
    Obs.Settings.Image("bg obs_forest_running3", "bg/obs_forest_running3.png")
    Obs.Settings.Image("bg obs_forest_running3_red", "bg/obs_forest_running3_red.png")
    Obs.Settings.Image("bg obs_forest_running4", "bg/obs_forest_running4.png")
    Obs.Settings.Image("bg obs_forest_running5", "bg/obs_forest_running5.png")
    Obs.Settings.Image("bg obs_forest_running6", "bg/obs_forest_running6.png")
    Obs.Settings.Image("bg obs_forest_running7", "bg/obs_forest_running7.png")
    Obs.Settings.Image("bg obs_art_room_window_gray", "bg/obs_art_room_window_gray.png")
    Obs.Settings.Image("bg obs_art_room_window_gray_layer", "objects/obs_art_room_window_gray_layer.png")
    Obs.Settings.Image("bg obs_art_monitor_gray", obs_rotate_repeat_at_bg("bg/obs_art_monitor_gray.png", "objects/obs_arrow.png", "objects/obs_clock.png", 0.11, 0.205))
    Obs.Settings.Image("bg obs_art_room_gray", "bg/obs_art_room_gray.png")
    Obs.Settings.Image("bg obs_art_room_layer_gray", "objects/obs_art_room_layer_gray.png")
    Obs.Settings.Image("bg obs_art_room2_gray", "bg/obs_art_room2_gray.png")
    Obs.Settings.Image("bg obs_art_room2_layer_gray", "objects/obs_art_room2_layer_gray.png")
    Obs.Settings.Image("bg obs_art_kitchen", "bg/obs_art_kitchen.png")
    Obs.Settings.Image("bg obs_art_kitchen_gray", "bg/obs_art_kitchen_gray.png")
    Obs.Settings.Image("bg obs_police_station", "bg/obs_police_station.png")
    Obs.Settings.Image("bg obs_police_station_phone", "bg/obs_police_station_phone.png")
    Obs.Settings.Image("bg obs_ext_school", "bg/obs_ext_school.png")
    Obs.Settings.Image("bg obs_city", "bg/obs_city.png")
    Obs.Settings.Image("bg obs_forest", "bg/obs_forest.png")
    Obs.Settings.Image("bg obs_forest2", "bg/obs_forest2.png")
    Obs.Settings.Image("bg obs_forest3", "bg/obs_forest3.png")
    Obs.Settings.Image("bg obs_forest4", "bg/obs_forest4.png")
    Obs.Settings.Image("bg obs_forest_house", "objects/obs_forest_house.png")
    Obs.Settings.Image("bg obs_forest_house2", "objects/obs_forest_house2.png")
    Obs.Settings.Image("bg obs_forest_house3", "objects/obs_forest_house3.png")
    Obs.Settings.Image("bg obs_ext_forest_glade", "bg/obs_ext_forest_glade.png")
    Obs.Settings.Image("bg obs_ext_forest_glade2", "bg/obs_ext_forest_glade2.png")
    Obs.Settings.Image("bg obs_ext_camp_entrance_night_vision", "bg/obs_ext_camp_entrance_night_vision.png")
    Obs.Settings.Image("bg obs_ext_bus_light", "bg/obs_ext_bus_light.png")
    Obs.Settings.Image("bg obs_ext_bus_light2", "bg/obs_ext_bus_light2.png")
    Obs.Settings.Image("bg obs_ext_bus_light3", "bg/obs_ext_bus_light3.png")
    Obs.Settings.Image("bg obs_mi_cg_ground_no_mi", "cg/mi_musclub/obs_mi_cg_ground_no_mi.png")
    Obs.Settings.Image("bg obs_ext_musclub_verandah_day", "bg/obs_ext_musclub_verandah_day.png")
    Obs.Settings.Image("bg obs_ext_musclub_verandah_sunset", "bg/obs_ext_musclub_verandah_sunset.png")
    Obs.Settings.Image("bg obs_ext_musclub_verandah_night", "bg/obs_ext_musclub_verandah_night.png")
    Obs.Settings.Image("bg obs_int_dining_hall_people_sunset", "bg/obs_int_dining_hall_people_sunset.png")
    Obs.Settings.Image("bg obs_int_dining_dish_sunset", "bg/obs_int_dining_dish_sunset.png")
    Obs.Settings.Image("bg obs_int_dining_hall2_sunset", "bg/obs_int_dining_hall2_sunset.png")
    Obs.Settings.Image("bg obs_int_dining_table_day", "bg/obs_int_dining_table_day.png")
    Obs.Settings.Image("bg obs_int_dining_table_sunset", "bg/obs_int_dining_table_sunset.png")
    Obs.Settings.Image("bg obs_ext_dining_bench_day", "bg/obs_ext_dining_bench_day.png")
    Obs.Settings.Image("bg obs_ext_dining_bench_sunset", "bg/obs_ext_dining_bench_sunset.png")
    Obs.Settings.Image("bg obs_ext_musclub_sunset", "bg/obs_ext_musclub_sunset.png")
    Obs.Settings.Image("bg obs_ext_musclub_night", "bg/obs_ext_musclub_night.png")
    Obs.Settings.Image("bg obs_int_musclub_mattresses_day", "bg/obs_int_musclub_mattresses_day.png")
    Obs.Settings.Image("bg obs_int_musclub_mattresses_sunset", "bg/obs_int_musclub_mattresses_sunset.png")
    Obs.Settings.Image("bg obs_int_musclub_mattresses_night", "bg/obs_int_musclub_mattresses_night.png")
    Obs.Settings.Image("bg obs_ext_musclub_night_rain", "bg/obs_ext_musclub_night_rain.png")
    Obs.Settings.Image("bg obs_ext_houses_night_rain", "bg/obs_ext_houses_night_rain.png")
    Obs.Settings.Image("bg obs_ext_houses_night", "bg/obs_ext_houses_night.png")
    Obs.Settings.Image("bg obs_ext_house_of_un_night", "bg/obs_ext_house_of_un_night.png")
    Obs.Settings.Image("bg obs_int_house_of_un_right_side_night", "bg/obs_int_house_of_un_right_side_night.png")
    Obs.Settings.Image("bg obs_int_house_of_un_day", "bg/obs_int_house_of_un_day.png")
    Obs.Settings.Image("bg obs_int_house_of_un_day_horror", "bg/obs_int_house_of_un_day_horror.png")
    Obs.Settings.Image("bg obs_int_house_of_un_night", "bg/obs_int_house_of_un_night.png")
    Obs.Settings.Image("bg obs_int_house_of_un_night_mi_sleep", [Obs.Brightness(Obs.PathImg() + "bg/obs_int_house_of_un_night.png", -0.2), Obs.Brightness(Obs.PathImg() + "objects/obs_int_house_of_un_night_mi_sleep.png", -0.2)])
    Obs.Settings.Image("bg obs_int_dining_hall_a_few_people_day", "bg/obs_int_dining_hall_a_few_people_day.png")
    Obs.Settings.Image("bg obs_ext_houses2_day", "bg/obs_ext_houses2_day.png")
    Obs.Settings.Image("bg obs_ext_houses_winter_night", "bg/obs_ext_houses_winter_night.png")
    Obs.Settings.Image("bg obs_ext_house_of_mt_sunset_horror", "bg/obs_ext_house_of_mt_sunset_horror.png")
    Obs.Settings.Image("bg obs_ext_houses_sunset_horror", "bg/obs_ext_houses_sunset_horror.png")
    Obs.Settings.Image("bg obs_ext_stage_big_sunset", "bg/obs_ext_stage_big_sunset.png")
    Obs.Settings.Image("bg obs_ext_boathouse_day_anim", obs_boathouse_anim("day", -1.0, 2.0, 0.57))
    Obs.Settings.Image("bg obs_ext_boathouse_day", "bg/obs_ext_boathouse_day.png")
    Obs.Settings.Image("bg obs_ext_boathouse_sunset_anim", obs_boathouse_anim("sunset", -0.5, 1.5, 0.577))
    Obs.Settings.Image("bg obs_ext_boathouse_sunset", "bg/obs_ext_boathouse_sunset.png")
    Obs.Settings.Image("bg obs_ext_boathouse_night_anim", obs_boathouse_anim("night", 2.0, -1.0, 0.572))
    Obs.Settings.Image("bg obs_ext_boathouse_night", "bg/obs_ext_boathouse_night.png")
    Obs.Settings.Image("bg obs_ext_library_sunset", "bg/obs_ext_library_sunset.png")
    Obs.Settings.Image("bg obs_ext_aidpost_sunset", "bg/obs_ext_aidpost_sunset.png")
    Obs.Settings.Image("bg obs_int_house_of_dv_night_dark", "bg/obs_int_house_of_dv_night_dark.png")
    Obs.Settings.Image("bg obs_int_bus_winter_day", "bg/obs_int_bus_winter_day.png")
    Obs.Settings.Image("bg obs_int_house_of_dv_rain_blur", "bg/obs_int_house_of_dv_rain_blur.png")
    Obs.Settings.Image("bg obs_int_house_of_dv_rain", "bg/obs_int_house_of_dv_rain.png")
    Obs.Settings.Image("bg obs_ext_house_of_dv_rain", "bg/obs_ext_house_of_dv_rain.png")
    Obs.Settings.Image("bg obs_ext_houses_rain", "bg/obs_ext_houses_rain.png")
    Obs.Settings.Image("bg obs_ext_houses2_rain", "bg/obs_ext_houses2_rain.png")
    Obs.Settings.Image("bg obs_ext_clubs_rain", "bg/obs_ext_clubs_rain.png")
    Obs.Settings.Image("bg obs_ext_camp_entrance_rain", "bg/obs_ext_camp_entrance_rain.png")
    Obs.Settings.Image("bg obs_ext_path_rain", "bg/obs_ext_path_rain.png")
    Obs.Settings.Image("bg obs_ext_path2_rain", "bg/obs_ext_path2_rain.png")
    Obs.Settings.Image("bg obs_ext_washstand_rain", "bg/obs_ext_washstand_rain.png")
    Obs.Settings.Image("bg obs_ext_musclub_rain", "bg/obs_ext_musclub_rain.png")
    Obs.Settings.Image("bg obs_ext_square_rain_dark", "bg/obs_ext_square_rain_dark.png")
    Obs.Settings.Image("bg obs_ext_dinner_away_rain", "bg/obs_ext_dinner_away_rain.png")
    Obs.Settings.Image("bg obs_ext_dining_hall_near_rain", "bg/obs_ext_dining_hall_near_rain.png")
    Obs.Settings.Image("bg obs_int_dinning_hall_people_rain", "bg/obs_int_dinning_hall_people_rain.png")
    Obs.Settings.Image("bg obs_ext_aidpost_rain", "bg/obs_ext_aidpost_rain.png")
    Obs.Settings.Image("bg obs_int_aidpost_rain", "bg/obs_int_aidpost_rain.png")
    Obs.Settings.Image("bg obs_ext_square_rain", "bg/obs_ext_square_rain.png")
    Obs.Settings.Image("bg obs_ext_bus_stop_rain", "bg/obs_ext_bus_stop_rain.png")
    Obs.Settings.Image("bg obs_ext_mysterious_house_rain_gleam", "bg/obs_ext_mysterious_house_rain_gleam.png")
    Obs.Settings.Image("bg obs_ext_mysterious_house_rain1", "bg/obs_ext_mysterious_house_rain1.png")
    Obs.Settings.Image("bg obs_ext_mysterious_house_rain2", "bg/obs_ext_mysterious_house_rain2.png")
    Obs.Settings.Image("bg obs_ext_mysterious_house_rain3", "bg/obs_ext_mysterious_house_rain3.png")
    Obs.Settings.Image("bg obs_ext_mysterious_house_rain4", "bg/obs_ext_mysterious_house_rain4.png")
    Obs.Settings.Image("bg obs_ext_mysterious_house_rain5", "bg/obs_ext_mysterious_house_rain5.png")
    Obs.Settings.Image("bg obs_ext_mysterious_house_rain6", "bg/obs_ext_mysterious_house_rain6.png")
    Obs.Settings.Image("bg obs_ext_sky_rain", "bg/obs_ext_sky_rain.png")
    Obs.Settings.Image("bg obs_ext_square_houses_rain", "bg/obs_ext_square_houses_rain.png")
    Obs.Settings.Image("bg obs_ext_house_of_un_rain", "bg/obs_ext_house_of_un_rain.png")
    Obs.Settings.Image("bg obs_ext_house_of_un_open_door_rain", "bg/obs_ext_house_of_un_open_door_rain.png")
    Obs.Settings.Image("bg obs_int_house_of_un_rain", "bg/obs_int_house_of_un_rain.png")
    Obs.Settings.Image("bg obs_ext_house_of_un_outside", "objects/obs_ext_house_of_un_outside.png")
    Obs.Settings.Image("bg obs_ext_house_of_un_outside2", "objects/obs_ext_house_of_un_outside2.png")
    Obs.Settings.Image("bg obs_ext_house_of_un_behind_close_door", "bg/obs_ext_house_of_un_behind_close_door.png")
    Obs.Settings.Image("bg obs_int_house_of_un_ceiling_rain", "bg/obs_int_house_of_un_ceiling_rain.png")
    Obs.Settings.Image("bg obs_int_house_of_un_ceiling_rain2", "bg/obs_int_house_of_un_ceiling_rain2.png")
    Obs.Settings.Image("bg obs_ext_house_of_mt_without_light_rain", "bg/obs_ext_house_of_mt_without_light_rain.png")
    Obs.Settings.Image("bg obs_int_house_of_mt_rain", "bg/obs_int_house_of_mt_rain.png")
    Obs.Settings.Image("bg obs_ext_house_of_aln_rain", "bg/obs_ext_house_of_aln_rain.png")
    Obs.Settings.Image("bg obs_int_house_of_aln_rain_anim", ["objects/obs_int_house_of_aln_rain_ground.png", "obs_eff_hard_rain left2", "bg/obs_int_house_of_aln_rain_layer2.png"])
    Obs.Settings.Image("bg obs_int_house_of_aln_rain_dark_anim", ["objects/obs_int_house_of_aln_rain_ground_dark.png", "obs_eff_hard_rain left2", "bg/obs_int_house_of_aln_rain_layer2.png"])
    Obs.Settings.Image("bg obs_int_house_of_aln_cards_desk", "bg/obs_int_house_of_aln_cards_desk.png")
    Obs.Settings.Image("bg obs_int_house_of_aln_celling", "bg/obs_int_house_of_aln_celling.png")
    Obs.Settings.Image("bg obs_ext_house_of_aln_behind_close_door", "bg/obs_ext_house_of_aln_behind_close_door.png")
    Obs.Settings.Image("bg obs_ext_house_of_aln_rain_dark", "bg/obs_ext_house_of_aln_rain_dark.png")
    Obs.Settings.Image("bg obs_int_house_of_aln_rain_dark", "bg/obs_int_house_of_aln_rain_dark.png")
    Obs.Settings.Image("bg obs_ext_square_rain_dark_blue", "bg/obs_ext_square_rain_dark_blue.png")
    Obs.Settings.Image("bg obs_int_house_of_mt_rain_dark", "bg/obs_int_house_of_mt_rain_dark.png")



    Obs.Settings.Image("cg obs_prologue_art_room_gray", obs_rotate_repeat_at_bg("cg/art_mirror/obs_ground.png", "cg/art_mirror/obs_arrow.png", "cg/art_mirror/obs_clock.png", 0.151, 0.265))
    Obs.Settings.Image("cg obs_prologue_gang_pt_and_vdm", "cg/obs_prologue_gang_pt_and_vdm.png")
    Obs.Settings.Image("cg obs_prologue_gang_penetration_ground", "cg/gang_penetration/obs_ground.png")
    Obs.Settings.Image("cg obs_prologue_gang_fire_ground", "cg/gang_fire/obs_ground.png")
    Obs.Settings.Image("cg obs_prologue_gang_abandonment_ground", "cg/gang_abandonment/obs_ground.png")
    Obs.Settings.Image("cg obs_prologue_girls_attack", "cg/obs_prologue_girls_attack.png")
    Obs.Settings.Image("cg obs_prologue_street", "cg/obs_prologue_street.png")
    Obs.Settings.Image("cg obs_prologue_street2", "cg/obs_prologue_street2.png")
    Obs.Settings.Image("cg obs_prologue_school_memory", "cg/obs_prologue_school_memory.png")
    Obs.Settings.Image("cg obs_prologue_school_memory2", "cg/obs_prologue_school_memory2.png")
    Obs.Settings.Image("cg obs_prologue_school_memory3", "cg/obs_prologue_school_memory3.png")
    Obs.Settings.Image("cg obs_prologue_school_memory4", "cg/obs_prologue_school_memory4.png")
    Obs.Settings.Image("cg obs_prologue_school_memory5", "cg/obs_prologue_school_memory5.png")
    Obs.Settings.Image("cg obs_prologue_bus_ride", "cg/obs_prologue_bus_ride.png")
    Obs.Settings.Image("cg obs_prologue_bus_ride2", "cg/obs_prologue_bus_ride2.png")
    Obs.Settings.Image("cg obs_prologue_bus_ride3", "cg/obs_prologue_bus_ride3.png")
    Obs.Settings.Image("cg obs_prologue_bus_ride4", "cg/obs_prologue_bus_ride4.png")
    Obs.Settings.Image("cg obs_d1_sl_gate", "cg/obs_d1_sl_gate.png")
    Obs.Settings.Image("cg obs_d1_food_fork", "cg/obs_d1_food_fork.png")
    Obs.Settings.Image("cg obs_d1_art_dining1", ["cg/art_dining/obs_ground.png", "cg/art_dining/obs_mouth.png"])
    Obs.Settings.Image("cg obs_d1_art_dining2", ["cg/art_dining/obs_ground.png", "cg/art_dining/obs_mouth2.png"])
    Obs.Settings.Image("cg obs_d1_art_dining3", ["cg/art_dining/obs_ground.png", "cg/art_dining/obs_mouth3.png"])
    Obs.Settings.Image("cg obs_d1_mi_canteen_kiss", "cg/obs_d1_mi_canteen_kiss.png")
    Obs.Settings.Image("cg obs_d1_msk_canteen_rage", "cg/obs_d1_msk_canteen_rage.png")
    Obs.Settings.Image("cg obs_d1_art_and_mi_sitting_on_mattresses", "cg/art_and_mi_musclub/obs_ground.png")
    Obs.Settings.Image("cg obs_d1_mi_sitting_on_mattresses_ground_sunset", "cg/mi_sitting_on_mattresses/obs_ground_sunset.png")
    Obs.Settings.Image("cg obs_d1_mi_sitting_on_mattresses_ground_night", "cg/mi_sitting_on_mattresses/obs_ground_night.png")
    Obs.Settings.Image("cg obs_d1_mi_sitting_on_mattresses_ground_no_miku", "cg/mi_sitting_on_mattresses/obs_ground_no_miku.png")
    Obs.Settings.Image("cg obs_d1_two_in_the_subway_ground", "cg/two_in_the_subway/obs_ground.png")
    Obs.Settings.Image("cg obs_d2_mi_obsessed_eye",  "cg/obs_d2_mi_obsessed_eye.png")
    Obs.Settings.Image("cg obs_d2_art_murror_shirt", "cg/art_mirror2/obs_ground.png")
    Obs.Settings.Image("cg obs_d2_art_murror_pioneer", ["cg/art_mirror2/obs_ground.png", "cg/art_mirror2/obs_pioneer.png"])
    Obs.Settings.Image("cg obs_d2_art_murror_pioneer2", ["cg/art_mirror2/obs_ground.png", "cg/art_mirror2/obs_pioneer.png", "cg/art_mirror2/obs_mouth.png"])
    Obs.Settings.Image("cg obs_d2_locker_empty", "cg/locker/obs_ground.png")
    Obs.Settings.Image("cg obs_d2_locker_revolver", ["cg/locker/obs_ground.png", "cg/locker/obs_revolver.png"])
    Obs.Settings.Image("cg obs_d3_art_standing_on_the_road", "cg/obs_d3_art_standing_on_the_road.png")
    Obs.Settings.Image("cg obs_d3_mi_eye", "cg/obs_d3_mi_eye.png")
    Obs.Settings.Image("cg obs_d3_mi_sleeping_happily", "cg/obs_d3_mi_sleeping_happily.png")
    Obs.Settings.Image("cg obs_d3_cry_in_the_house", "cg/obs_d3_cry_in_the_house.png")
    Obs.Settings.Image("cg obs_d3_mi_gets_up_from_the_sidewalk", "cg/obs_d3_mi_gets_up_from_the_sidewalk.png")



    Obs.Settings.Image("obs_forest_running3_red_logo", "objects/obs_forest_running3_red_logo.png")
    Obs.Settings.Image("obs_forest_in_the_fog2_layer", "objects/obs_forest_in_the_fog2_layer.png")
    Obs.Settings.Image("obs_forest_in_the_fog2_layer2", "objects/obs_forest_in_the_fog2_layer2.png")
    Obs.Settings.Image("obs_monitor_layer_gray", "objects/obs_monitor_layer_gray.png")
    Obs.Settings.Image("obs_hand_for_monitor_gray", "objects/obs_hand_for_monitor_gray.png")
    Obs.Settings.Image("obs_art_room_layer", "cg/art_mirror/obs_layer.png")
    Obs.Settings.Image("obs_art_room_hand", "cg/art_mirror/obs_hand.png")
    Obs.Settings.Image("obs_art_room_branches", "cg/art_mirror/obs_branches.png")
    Obs.Settings.Image("obs_art_room_gray 2", "cg/art_mirror/obs_mouth.png")
    Obs.Settings.Image("obs_art_room_gray 3", "cg/art_mirror/obs_mouth2.png")
    Obs.Settings.Image("obs_art_room_gray 4", "cg/art_mirror/obs_mouth3.png")
    Obs.Settings.Image("obs_phone_on_the_chair normal", "objects/obs_art_room_phone_gray.png")
    Obs.Settings.Image("obs_phone_on_the_chair anim", ["objects/obs_art_room_phone_gray.png", At(Obs.PathImg() + "objects/obs_art_room_phone2_gray.png", obs_alpha_ease_repeat)])
    Obs.Settings.Image("obs_phone mihalich", obs_phone_blinking_contains_color(""))
    Obs.Settings.Image("obs_phone mihalich_gray", obs_phone_blinking_contains_color("_gray"))
    Obs.Settings.Image("obs_phone none", ["misc/phone/obs_phone_ground.png", "misc/phone/obs_phone_layer.png"])
    Obs.Settings.Image("obs_phone none_gray", ["misc/phone/obs_phone_ground.png", "misc/phone/obs_phone_layer_gray.png"])
    Obs.Settings.Image("obs_phone none_jacket", ["misc/phone/obs_phone_ground.png", "misc/phone/obs_phone_layer2.png"])
    Obs.Settings.Image("obs_phone none_jacket_gray", ["misc/phone/obs_phone_ground.png", "misc/phone/obs_phone_layer2_gray.png"])
    Obs.Settings.Image("obs_phone none_gray", ["misc/phone/obs_phone_ground_gray.png", "misc/phone/obs_phone_layer_gray.png"])
    Obs.Settings.Image("obs_phone off", ["misc/phone/obs_phone_ground2.png", "misc/phone/obs_phone_layer.png"])
    Obs.Settings.Image("obs_phone off_gray", ["misc/phone/obs_phone_ground2.png", "misc/phone/obs_phone_layer_gray.png"])
    Obs.Settings.Image("obs_phone temperature_jacket_gray", ["misc/phone/obs_phone_ground3.png", "misc/phone/obs_phone_layer2_gray.png"])
    Obs.Settings.Image("obs_prologue_gang_fire_layer 1", "cg/gang_fire/obs_layer.png")
    Obs.Settings.Image("obs_prologue_gang_fire_layer 2", "cg/gang_fire/obs_layer2.png")
    Obs.Settings.Image("obs_prologue_gang_fire_molotov", "cg/gang_fire/obs_molotov.png")
    Obs.Settings.Image("obs_prologue_gang_fire_flame", obs_seven_anim("cg/gang_fire/obs_flame"))
    Obs.Settings.Image("obs_prologue_gang_penetration_pt 1", "cg/gang_penetration/obs_pt1.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_pt 2", "cg/gang_penetration/obs_pt2.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_pt 3", "cg/gang_penetration/obs_pt3.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_vdm 1", "cg/gang_penetration/obs_vdm1.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_vdm 2", "cg/gang_penetration/obs_vdm2.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_vdm 3", "cg/gang_penetration/obs_vdm3.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_msk 1", "cg/gang_penetration/obs_msk1.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_msk 2", "cg/gang_penetration/obs_msk2.png")
    Obs.Settings.Image("obs_prologue_gang_penetration_msk 3", "cg/gang_penetration/obs_msk3.png")
    Obs.Settings.Image("obs_prologue_gang_penetration cop", "cg/gang_penetration/obs_cop.png")
    Obs.Settings.Image("obs_prologue_gang_abandonment_humans 1", "cg/gang_abandonment/obs_humans1.png")
    Obs.Settings.Image("obs_prologue_gang_abandonment_humans 2", "cg/gang_abandonment/obs_humans2.png")
    Obs.Settings.Image("obs_prologue_gang_abandonment dogs", "cg/gang_abandonment/obs_dogs.png")
    Obs.Settings.Image("obs_girls_attack_layer", "objects/obs_girls_attack_layer.png")
    Obs.Settings.Image("obs_art_name", "misc/names/obs_art_name.png")
    Obs.Settings.Image("obs_art_name2", "misc/names/obs_art_name2.png")
    Obs.Settings.Image("obs_msk_name", "misc/names/obs_msk_name.png")
    Obs.Settings.Image("obs_msk_name2", "misc/names/obs_msk_name2.png")
    Obs.Settings.Image("obs_mi_name", "misc/names/obs_mi_name.png")
    Obs.Settings.Image("obs_mi_name2", "misc/names/obs_mi_name2.png")
    Obs.Settings.Image("obs_explosion", "misc/else/obs_explosion.png")
    Obs.Settings.Image("obs_flame_frame", "misc/else/obs_flame_frame.png")
    Obs.Settings.Image("obs_skull", "misc/else/obs_skull.png")
    Obs.Settings.Image("obs_chair", obs_matrix_color("misc/else/obs_chair.png"))
    Obs.Settings.Image("obs_police_station_phone_layer", "objects/obs_police_station_phone_layer.png")
    Obs.Settings.Image("obs_police_station_phone_layer2", "objects/obs_police_station_phone_layer2.png")
    Obs.Settings.Image("obs_police_station_phone_layer3", "objects/obs_police_station_phone_layer3.png")
    Obs.Settings.Image("obs_intro_xx_layer", "objects/obs_intro_xx_layer.png")
    Obs.Settings.Image("obs_forest_layer 1", "objects/obs_forest_layer.png")
    Obs.Settings.Image("obs_forest_layer 2", "objects/obs_forest_layer2.png")
    Obs.Settings.Image("obs_forest4_house 1", "objects/obs_forest4_house.png")
    Obs.Settings.Image("obs_forest4_house 2", "objects/obs_forest4_house2.png")
    Obs.Settings.Image("obs_forest4_layer", "objects/obs_forest4_layer.png")
    Obs.Settings.Image("obs_forest_house_layer", At(Obs.PathImg() + "objects/obs_forest_house_layer.png", obs_ypos(1.0)))
    Obs.Settings.Image("obs_forest_house_layer2", At(Obs.PathImg() + "objects/obs_forest_house_layer2.png", obs_ypos(0.01)))
    Obs.Settings.Image("obs_forest_house_layer3", At(Obs.PathImg() + "objects/obs_forest_house_layer3.png", obs_ypos(-0.97)))
    Obs.Settings.Image("obs_forest_house_layer4", At(Obs.PathImg() + "objects/obs_forest_house_layer4.png", obs_ypos(-1.96)))
    Obs.Settings.Image("obs_forest_house_layer5", At(Obs.PathImg() + "objects/obs_forest_house_layer5.png", obs_ypos(-2.944)))
    Obs.Settings.Image("obs_forest_house_horror", "objects/obs_forest_house_horror.png")
    Obs.Settings.Image("obs_ext_forest_glade_ghosts 1", "objects/obs_ext_forest_glade_ghosts.png")
    Obs.Settings.Image("obs_ext_forest_glade_ghosts 2", "objects/obs_ext_forest_glade_ghosts2.png")
    Obs.Settings.Image("obs_ext_forest_glade_ghosts_attack 1", "objects/obs_ext_forest_glade_ghosts_attack.png")
    Obs.Settings.Image("obs_ext_forest_glade_ghosts_attack 2", "objects/obs_ext_forest_glade_ghosts_attack2.png")
    Obs.Settings.Image("obs_old_building_lurking_mi_red", "objects/obs_old_building_lurking_mi_red.png")
    Obs.Settings.Image("obs_art_kitchen_backpack_gray", "objects/obs_art_kitchen_backpack_gray.png")
    Obs.Settings.Image("obs_ext_camp_entrance_night_vision_layer", "objects/obs_ext_camp_entrance_night_vision_layer.png")
    Obs.Settings.Image("obs_ext_camp_entrance_night_vision_uvao", "objects/obs_ext_camp_entrance_night_vision_uvao.png")
    Obs.Settings.Image("obs_ext_bus_light_hand", "objects/obs_ext_bus_light_hand.png")
    Obs.Settings.Image("obs_ext_boathouse_shadow", "objects/obs_ext_boathouse_shadow.png")
    Obs.Settings.Image("obs_ext_boathouse_layer", "objects/obs_ext_boathouse_layer.png")
    Obs.Settings.Image("obs_int_dining_table_layer_day", "objects/obs_int_dining_table_layer_day.png")
    Obs.Settings.Image("obs_int_dining_table_layer_sunset", "objects/obs_int_dining_table_layer_sunset.png")
    Obs.Settings.Image("obs_int_dining_table_layer2_sunset", "objects/obs_int_dining_table_layer2_sunset.png")
    Obs.Settings.Image("obs_int_dining_table_sunset_mi_blur", "objects/obs_int_dining_table_sunset_mi_blur.png")
    Obs.Settings.Image("obs_ext_dining_bench_day_layer", "objects/obs_ext_dining_bench_day_layer.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_art smile", "cg/art_and_mi_musclub/obs_art_smile.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_art surprise", "cg/art_and_mi_musclub/obs_art_surprise.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_mi smile", "cg/art_and_mi_musclub/obs_mi_smile.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_mi sad", "cg/art_and_mi_musclub/obs_mi_sad.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_mi surprise", "cg/art_and_mi_musclub/obs_mi_surprise.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_mi shy_smile", "cg/art_and_mi_musclub/obs_mi_shy_smile.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_mi shy_sad", "cg/art_and_mi_musclub/obs_mi_shy_sad.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_mi shy_surprise", "cg/art_and_mi_musclub/obs_mi_shy_surprise.png")
    Obs.Settings.Image("obs_d1_art_and_mi_sitting_on_mattresses_mi obsessed_surprise", "cg/art_and_mi_musclub/obs_mi_obsessed_surprise.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_brows happy_sunset", "cg/mi_sitting_on_mattresses/obs_brows_happy_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_brows sad_sunset", "cg/mi_sitting_on_mattresses/obs_brows_sad_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_eyes close_sunset", "cg/mi_sitting_on_mattresses/obs_eyes_close_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_eyes open_sunset", "cg/mi_sitting_on_mattresses/obs_eyes_open_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_eyes obsessed_sunset", "cg/mi_sitting_on_mattresses/obs_eyes_obsessed_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth grin_sunset", "cg/mi_sitting_on_mattresses/obs_mouth_grin_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth happy_sunset", "cg/mi_sitting_on_mattresses/obs_mouth_happy_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth normal_sunset", "cg/mi_sitting_on_mattresses/obs_mouth_normal_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth smile_sunset", "cg/mi_sitting_on_mattresses/obs_mouth_smile_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth smile2_sunset", "cg/mi_sitting_on_mattresses/obs_mouth_smile2_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth obsessed_sunset", "cg/mi_sitting_on_mattresses/obs_mouth_obsessed_sunset.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_brows happy_night", "cg/mi_sitting_on_mattresses/obs_brows_happy_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_brows sad_night", "cg/mi_sitting_on_mattresses/obs_brows_sad_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_eyes close_night", "cg/mi_sitting_on_mattresses/obs_eyes_close_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_eyes open_night", "cg/mi_sitting_on_mattresses/obs_eyes_open_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth grin_night", "cg/mi_sitting_on_mattresses/obs_mouth_grin_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth happy_night", "cg/mi_sitting_on_mattresses/obs_mouth_happy_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth normal_night", "cg/mi_sitting_on_mattresses/obs_mouth_normal_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth smile_night", "cg/mi_sitting_on_mattresses/obs_mouth_smile_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_mouth smile2_night", "cg/mi_sitting_on_mattresses/obs_mouth_smile2_night.png")
    Obs.Settings.Image("obs_d1_mi_sitting_on_mattresses_light_layer", "cg/mi_sitting_on_mattresses/obs_light_layer.png")
    Obs.Settings.Image("obs_d1_two_in_the_subway_unk1 1", "cg/two_in_the_subway/obs_unk1_1.png")
    Obs.Settings.Image("obs_d1_two_in_the_subway_unk1 2", "cg/two_in_the_subway/obs_unk1_2.png")
    Obs.Settings.Image("obs_d1_two_in_the_subway_unk2 1", "cg/two_in_the_subway/obs_unk2_1.png")
    Obs.Settings.Image("obs_d1_two_in_the_subway_unk2 2", "cg/two_in_the_subway/obs_unk2_2.png")
    Obs.Settings.Image("obs_d1_two_in_the_subway_unk2 3", "cg/two_in_the_subway/obs_unk2_3.png")
    Obs.Settings.Image("obs_int_mi_house_shadow", "objects/obs_int_mi_house_shadow.png")
    Obs.Settings.Image("obs_int_mi_house_shadow2", "objects/obs_int_mi_house_shadow2.png")
    Obs.Settings.Image("obs_vignette2", "effects/obs_vignette2.png")
    Obs.Settings.Image("obs_blood_light 1", "effects/obs_blood_light.png")
    Obs.Settings.Image("obs_blood_light 2", "effects/obs_blood_light2.png")
    Obs.Settings.Image("obs_blood_light 3", "effects/obs_blood_light3.png")
    Obs.Settings.Image("obs_revolver", "effects/obs_revolver.png")
    Obs.Settings.Image("obs_revolver2", "effects/obs_revolver2.png")
    Obs.Settings.Image("obs_talking_board", "objects/obs_talking_board.png")
    Obs.Settings.Image("obs_gleam", Transform(Obs.PathImg() + "objects/obs_gleam.png", pos=(780, 770)))
    Obs.Settings.Image("obs_flashlight", "objects/obs_flashlight.png")
    Obs.Settings.Image("obs_medallion", "objects/obs_medallion.png")
    Obs.Settings.Image("obs_hand_medallion", "objects/obs_hand_medallion.png")
    Obs.Settings.Image("obs_hand_medallion_blue", "objects/obs_hand_medallion_blue.png")
    Obs.Settings.Image("obs_hand_medallion_purple", "objects/obs_hand_medallion_purple.png")
    Obs.Settings.Image("obs_bag", "objects/obs_bag.png")
    Obs.Settings.Image("obs_phone_break 1", "misc/phone/obs_phone_break.png")
    Obs.Settings.Image("obs_phone_break 2", "misc/phone/obs_phone_break2.png")
    Obs.Settings.Image("obs_smoke3", "effects/obs_smoke3.png")
    Obs.Settings.Image("obs_smoke4", "effects/obs_smoke4.png")
    Obs.Settings.Image("obs_darkening", "effects/obs_darkening.png")
    Obs.Settings.Image("obs_fast_wind", "effects/obs_fast_wind.png")
    Obs.Settings.Image("obs_ext_house_of_un_behind_open_door", "objects/obs_ext_house_of_un_behind_open_door.png")
    Obs.Settings.Image("obs_int_house_of_mt_rain_layer 1", "objects/obs_int_house_of_mt_rain_layer.png")
    Obs.Settings.Image("obs_int_house_of_mt_rain_layer 2", "objects/obs_int_house_of_mt_rain_layer2.png")
    Obs.Settings.Image("obs_int_house_of_mt_rain_layer 3", "objects/obs_int_house_of_mt_rain_layer3.png")
    Obs.Settings.Image("obs_int_house_of_mt_rain_layer 4", "objects/obs_int_house_of_mt_rain_layer4.png")
    Obs.Settings.Image("obs_int_house_of_mt_rain_layer 5", "objects/obs_int_house_of_mt_rain_layer5.png")
    Obs.Settings.Image("obs_int_house_of_mt_rain_layer 6", "objects/obs_int_house_of_mt_rain_layer6.png")
    Obs.Settings.Image("obs_int_house_of_mt_rain_fantomas_eyes", "objects/obs_int_house_of_mt_rain_fantomas_eyes.png")
    Obs.Settings.Image("obs_int_house_of_aln_rain_layer", "objects/obs_int_house_of_aln_rain_layer.png")
    Obs.Settings.Image("obs_hands", "objects/obs_hands.png")
    Obs.Settings.Image("obs_art_kissed 1", "objects/obs_art_kissed.png")
    Obs.Settings.Image("obs_art_kissed 2", ["objects/obs_art_kissed.png", "objects/obs_art_kissed_layer.png"])
    Obs.Settings.Image("obs_art_and_mi", "objects/obs_art_and_mi.png")
    Obs.Settings.Image("obs_msk_phone 1", ["objects/obs_msk_phone1.png", "objects/obs_msk_phone_ground.png"])
    Obs.Settings.Image("obs_msk_phone 2", ["objects/obs_msk_phone2.png", "objects/obs_msk_phone_ground.png"])
    Obs.Settings.Image("obs_msk_phone 3", ["objects/obs_msk_phone3.png", "objects/obs_msk_phone_ground.png"])
    Obs.Settings.Image("obs_msk_phone 4", ["objects/obs_msk_phone4.png", "objects/obs_msk_phone_ground.png"])
    Obs.Settings.Image("obs_msk_phone 5", ["objects/obs_msk_phone5.png", "objects/obs_msk_phone_ground.png"])
    Obs.Settings.Image("obs_int_house_of_aln_rain_dark_layer", "bg/obs_int_house_of_aln_rain_dark_layer.png")
    Obs.Settings.Image("obs_msk_linked_msk_and_el", "objects/obs_msk_linked_msk_and_el.png")
    Obs.Settings.Image("obs_msk_linked_un", "objects/obs_msk_linked_un.png")
    Obs.Settings.Image("obs_msk_linked_msk sad", "objects/obs_msk_linked_msk_sad.png")
    Obs.Settings.Image("obs_msk_linked_el grin", "objects/obs_msk_linked_el_grin.png")
    Obs.Settings.Image("obs_msk_linked_el normal", "objects/obs_msk_linked_el_normal.png")
    Obs.Settings.Image("obs_ext_square_rain_dark_blue_mi 1", "objects/obs_ext_square_rain_dark_blue_mi.png")
    Obs.Settings.Image("obs_ext_square_rain_dark_blue_mi 2", "objects/obs_ext_square_rain_dark_blue_mi2.png")
    Obs.Settings.Image("obs_ext_square_rain_dark_blue_mi 3", "objects/obs_ext_square_rain_dark_blue_mi3.png")
    Obs.Settings.Image("obs_ext_square_rain_dark_blue_mi_normal", "objects/obs_ext_square_rain_dark_blue_mi_normal.png")



    Obs.Settings.Image("obs_game_time", DynamicDisplayable(Obs.GameTime))
    Obs.Settings.Image("obs_session_time", DynamicDisplayable(Obs.SessionTime))
    Obs.Settings.Image("obs_main_menu_background", "gui/main_menu/background.png")
    Obs.Settings.Image("obs_main_menu_layer", "gui/main_menu/layer.png")
    Obs.Settings.Image("obs_main_menu_layer2", "gui/main_menu/layer2.png")
    Obs.Settings.Image("obs_main_menu_bus", "gui/main_menu/bus.png")
    Obs.Settings.Image("obs_main_menu_mi", obs_main_menu_mi_move("gui/main_menu/mi"))
    Obs.Settings.Image("obs_main_menu_art_and_msk", "gui/main_menu/art_and_msk.png")
    Obs.Settings.Image("obs_main_menu_logo", "gui/main_menu/logo.png")
    Obs.Settings.Image("obs_main_menu_ground", "gui/main_menu/ground.png")
    Obs.Settings.Image("obs_main_menu_eye", Animation(Obs.PathImg() + "gui/main_menu/eye3.png", 0.5, Obs.PathImg() + "gui/main_menu/eye2.png", 0.5, Obs.PathImg() + "gui/main_menu/eye1.png", 0.5, Obs.PathImg() + "gui/main_menu/eye3.png", 0.5, Obs.PathImg() + "gui/main_menu/eye2.png", 0.5))
    Obs.Settings.Image("obs_main_menu_hand", "gui/main_menu/hand.png")
    Obs.Settings.Image("obs_version_text", ParameterizedText(style="obs_version_text", size=60))
    Obs.Settings.Image("obs_phone_text_icon", "gui/text/obs_phone_text_icon.png")
    Obs.Settings.Image("obs_censure_text_icon", "gui/text/obs_censure_text_icon.png")
    Obs.Settings.Image("obs_ctc_animation", obs_ctc_animation_for_time_of_day(0.905, 0.98))
    Obs.Settings.Image("obs_ctc_animation_nvl", obs_ctc_animation_for_time_of_day(0.920, 0.96))
    Obs.Settings.Image("obs_loading_icon", "gui/loading/icon.png")



    Obs.Settings.Image("obs_vignette", "effects/obs_vignette.png")
    Obs.Settings.Image("obs_vignette2", "effects/obs_vignette2.png")
    Obs.Settings.Image("obs_vignette3", "effects/obs_vignette3.png")
    Obs.Settings.Image("obs_blood_anim", obs_pause_dissolve_repeat("obs_blood", "obs_blood2"))
    Obs.Settings.Image("obs_interference_anim", obs_four_contains_xyzoom_effects("obs_interference"))
    Obs.Settings.Image("obs_smoke", obs_ease_slowly_repeat("smoke1", "smoke2"))
    Obs.Settings.Image("obs_smoke_red", obs_ease_slowly_repeat("smoke1_red", "smoke2_red"))
    Obs.Settings.Image("obs_prologue_dream_red", Animation(obs_redtint("images/anim/prologue_1.png"), 0.1, obs_redtint("images/anim/prologue_2.png"), 0.1, obs_redtint("images/anim/prologue_3.png"), 0.1))
    Obs.Settings.Image("obs_snow right", obs_linear_effects_repeat("snow", 0.75, 0.7, 0.75, 0.25, 0.3, 0.25))
    Obs.Settings.Image("obs_snow right2", obs_linear_effects_repeat("snow", 0.65, 0.6, 0.65, 0.35, 0.4, 0.35))
    Obs.Settings.Image("obs_snow right3", obs_linear_effects_repeat("snow", 0.5, 0.6, 0.75, 0.4, 0.5, 0.65))
    Obs.Settings.Image("obs_snow left", obs_linear_effects_repeat("snow", 0.75, 0.7, 0.75, 0.25, 0.3, 0.25, -1))
    Obs.Settings.Image("obs_snow left2", obs_linear_effects_repeat("snow", 0.65, 0.6, 0.65, 0.35, 0.4, 0.35, -1))
    Obs.Settings.Image("obs_snow left3", obs_linear_effects_repeat("snow", 0.5, 0.6, 0.75, 0.4, 0.5, 0.65, -1))
    Obs.Settings.Image("obs_snow right_red", obs_linear_effects_repeat("snow_red", 0.75, 0.7, 0.75, 0.25, 0.3, 0.25))
    Obs.Settings.Image("obs_dust1", obs_dust_alpha_linear_repeat(1, 10.0, 14.0))
    Obs.Settings.Image("obs_dust2", obs_dust_alpha_linear_repeat(2, 28.0, 32.0))
    Obs.Settings.Image("obs_dust3", obs_dust_alpha_linear_repeat(3, 13.0, 17.0))
    Obs.Settings.Image("obs_dust4", obs_dust_alpha_linear_repeat(4, 15.0, 19.0))
    Obs.Settings.Image("obs_dust5", obs_dust_alpha_linear_repeat(5, 10.0, 14.0))
    Obs.Settings.Image("obs_dust6", obs_dust_alpha_linear_repeat(6, 28.0, 32.0))
    Obs.Settings.Image("obs_dust7", obs_dust_alpha_linear_repeat(7, 13.0, 17.0))
    Obs.Settings.Image("obs_dust8", obs_dust_alpha_linear_repeat(8, 15.0, 19.0))
    Obs.Settings.Image("obs_dust9", obs_dust_alpha_linear_repeat(9, 10.0, 14.0))
    Obs.Settings.Image("obs_dust10", obs_dust_alpha_linear_repeat(10, 28.0, 32.0))
    Obs.Settings.Image("obs_dust11", obs_dust_alpha_linear_repeat(11, 13.0, 17.0))
    Obs.Settings.Image("obs_dust12", obs_dust_alpha_linear_repeat(12, 15.0, 19.0))
    Obs.Settings.Image("obs_l_light", obs_light_and_dust_contains("obs_l_light"))
    Obs.Settings.Image("obs_r_light", obs_light_and_dust_contains("obs_r_light"))
    Obs.Settings.Image("obs_c_light", ["obs_r_light", "obs_l_light"])
    Obs.Settings.Image("obs_l_light_ever", ["effects/obs_l_light.png", "obs_dust5", "obs_dust6", "obs_dust7", "obs_dust8", "obs_dust11", "obs_dust12"])
    Obs.Settings.Image("obs_r_light_ever", ["effects/obs_r_light.png", "obs_dust5", "obs_dust6", "obs_dust7", "obs_dust8", "obs_dust11", "obs_dust12"])
    Obs.Settings.Image("obs_c_light_ever", ["obs_r_light_ever", "obs_l_light_ever"])
    Obs.Settings.Image("obs_l_dust_ever", ["obs_dust5", "obs_dust6", "obs_dust7", "obs_dust8", "obs_dust11", "obs_dust12"])
    Obs.Settings.Image("obs_r_dust_ever", ["obs_dust5", "obs_dust6", "obs_dust7", "obs_dust8", "obs_dust11", "obs_dust12"])
    Obs.Settings.Image("obs_c_dust_ever", ["obs_r_dust_ever", "obs_l_dust_ever"])
    Obs.Settings.Image("obs_wind_anim", At(Animation(Obs.PathImg() + "effects/obs_wind.png", 0.1, Obs.PathImg() + "effects/obs_wind2.png", 0.1, Obs.PathImg() + "effects/obs_wind3.png", 0.1), obs_alpha(0.2))) 
    Obs.Settings.Image("obs_noise", obs_combine_effect("obs_noise1", "obs_noise2", "obs_noise3", "obs_noise4"))
    Obs.Settings.Image("obs_fast_wind_anim", Animation(Obs.PathImg() + "effects/obs_fast_wind.png", 0.1, Obs.PathImg() + "effects/obs_fast_wind2.png", 0.1, Obs.PathImg() + "effects/obs_fast_wind3.png", 0.1))
    Obs.Settings.Image("obs_broken_glass", "effects/obs_broken_glass.png")
    Obs.Settings.Image("obs_rage_anim", obs_dspr_repeat_move("obs_rage"))
    Obs.Settings.Image("obs_fight_anim", obs_dspr_repeat_move("obs_fight"))
    Obs.Settings.Image("obs_breeze_anim", obs_xalign_repeat_move("obs_breeze"))
    Obs.Settings.Image("obs_blood_light_anim", Animation(Obs.PathImg() + "effects/obs_blood_light.png", 0.5, Obs.PathImg() + "effects/obs_blood_light2.png", 0.5))
    Obs.Settings.Image("obs_blood_anim", Animation(Obs.PathImg() + "effects/obs_blood.png", 0.5, Obs.PathImg() + "effects/obs_blood2.png", 0.5))
    Obs.Settings.Image("obs_darkening_anim", Animation(Obs.PathImg() + "effects/obs_darkening.png", 0.5, Obs.PathImg() + "effects/obs_darkening2.png", 0.5))
    Obs.Settings.Image("obs_eff_rain", obs_effect_blossom("obs_raindrop_large", "obs_raindrop_normal", "obs_raindrop_small"))
    Obs.Settings.Image("obs_eff_rain2", obs_effect_blossom("obs_raindrop_large2", "obs_raindrop_normal2", "obs_raindrop_small2"))
    Obs.Settings.Image("obs_eff_rain3", obs_effect_blossom("obs_raindrop_large3", "obs_raindrop_normal3", "obs_raindrop_small3"))
    Obs.Settings.Image("obs_eff_hard_rain center", ["obs_eff_rain", "obs_eff_rain"])
    Obs.Settings.Image("obs_eff_hard_rain center2", ["obs_eff_rain2", "obs_eff_rain2"])
    Obs.Settings.Image("obs_eff_hard_rain center3", ["obs_eff_rain3", "obs_eff_rain3"])
    Obs.Settings.Image("obs_eff_hard_rain left", [Transform("obs_eff_rain", rotate=16), Transform("obs_eff_rain", rotate=16)])
    Obs.Settings.Image("obs_eff_hard_rain left2", [Transform("obs_eff_rain2", rotate=16), Transform("obs_eff_rain2", rotate=16)])
    Obs.Settings.Image("obs_eff_hard_rain left3", [Transform("obs_eff_rain3", rotate=16), Transform("obs_eff_rain3", rotate=16)])
    Obs.Settings.Image("obs_eff_hard_rain right", [Transform("obs_eff_rain", rotate=-16), Transform("obs_eff_rain", rotate=-16)])
    Obs.Settings.Image("obs_eff_hard_rain right2", [Transform("obs_eff_rain2", rotate=-16), Transform("obs_eff_rain2", rotate=-16)])
    Obs.Settings.Image("obs_eff_hard_rain right3", [Transform("obs_eff_rain3", rotate=-16), Transform("obs_eff_rain3", rotate=-16)])
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
