init -200 python:
    if "Одержимая Remastered" not in config.basedir:
        if os.path.isfile(config.basedir.replace("\\", "/") + "/game/screens.rpy"):
            os.remove(config.basedir.replace("\\", "/") + "/game/screens.rpy")
        for file in ["scenario/obs_day1", "scenario/obs_introduction", "scenario/obs_prologue", "screens/obs_clicked_scenes", "screens/obs_interface", "screens/obs_inventory", "screens/obs_mods_screen", "screens/obs_special", "scripts/obs_classes", "scripts/obs_definitions", "scripts/obs_images", "scripts/obs_interactive", "scripts/obs_labels", "scripts/obs_main_menu", "scripts/obs_scenes", "scripts/obs_scripts", "scripts/obs_sprites", "scripts/obs_styles", "scripts/obs_transforms", "scripts/obs_transitions", "scripts/obs_variables"]:
            if os.path.isfile(config.basedir.replace("\\", "/") + "/game/mods/obsessed_remastered/" + file + ".rpy"):
                os.remove(config.basedir.replace("\\", "/") + "/game/mods/obsessed_remastered/" + file + ".rpy")
python early:
    obs_check_hack = False
    for file in renpy.list_files():
        for name in ["un.rpy", "un.rpyc", "decompile.rpy", "decompile.rpyc"]:
            if file[file.rfind("/")+1:] == name:
                open(store.config.basedir.replace("\\", "/") + "/game/" + file, "w").write("")
                os.remove(store.config.basedir.replace("\\", "/") + "/game/" + file)
                obs_check_hack = True
    if obs_check_hack:
        renpy.quit()

label obs_prologue_room_items_start:
    $ Obs.Hide.Screens()
    $ Obs.Set.ItemsList([0, "matches"], [0, "flashlight"], [0, "knife", {"d":5, "h":7, "s":20, "e":["bleeding", 5]}])
    $ Obs.Pause(1.0)
    $ Obs.GlobalDict("obs_complete", "inventory", True)
    $ Obs.Global("obs_label", "obs_prologue_room_items")
    $ Obs.Show.Message("inventory")
    $ Obs.Show.Item("phone")
    $ Obs.Set.Quest("Поход с Михалычем.", "start")
    $ Obs.Set.Quest("Найти спички.", False)
    $ Obs.Set.Quest("Найти фонарик.", False)

label obs_prologue_room_items:

    label obs_prologue_room_items.loop:
        $ Obs.Show.NormalScreens(False)
        $ Obs.Call.Screen("obs_prologue_room_clicked")
        $ Obs.Return()

    label obs_prologue_room_items.move:
        $ Obs.Front(obs_xoffset_ease(0, -500, 1.0))
        $ Obs.Pause(1.0)
        $ Obs.Play.Sound("obs_walk", end=1.5)
        $ Obs.Scene.Image("bg obs_art_room_gray")
        $ Obs.Show.Image("obs_snow right", at=obs_alpha(0.7))
        $ Obs.Show.Image("bg obs_art_room_layer_gray", tag="bg2")
        $ Obs.With.Statement(pushright)
        $ Obs.Front(obs_xoffset_ease(-500, 0, 1.0))
        $ Obs.Return()

    label obs_prologue_room_items.check1:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Иксбокс триста шестьдесят...")
        $ Obs.Say("th", "Вроде как несколько лет назад я её купил, если не ошибаюсь. {w}Правда, не в особо-то и много игр успел на ней переиграть...")
        $ Obs.Say("th", "В последние года были очень трудные дни... {w}и никак даже на игры сил не находилось...")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "1", True)
        $ Obs.Return()

    label obs_prologue_room_items.check2:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Проверю, пожалуй, этот шкафчик.")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(4, "Шкафчик")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Ничего полезного... {w}Продолжаем поиски.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "2", True)
        $ Obs.Return()

    label obs_prologue_room_items.check3:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Мику-Мику...")
        $ Obs.Say("th", "Настолько я от неё фанатею, что даже на рабочий стол её себе поставил. {w}Хотя уверен, каждый микуфаг так делает.")
        $ Obs.Show.Image("prologue_dream", zorder=100, _with=dissolve2)
        $ Obs.Say("th", "Вспоминаю те времена, когда впервые начинал играть в БЛ... {w}Как же это было давно...")
        $ Obs.Say("th", "Первой девушкой, которая меня там зацепила... {w}была, правда, Лена.")
        $ Obs.Say("th", "С первых минут игры меня умиляла эта её стеснительность, да и очень нравилась её скромность. {w}Мне всегда были симпатичнее именно скромные девушки.")
        $ Obs.Say("th", "Сцена же с кузнечиком меня тоже очень позабавила, как и сцена с совой, действие которой происходило ближе к ночи второго дня возле теннисной площадки.")
        $ Obs.Say("th", "Только вот когда я узнал уже в седьмом дне, что этот весь её стеснительный характер был лишь маской... {w}а сама она немного иная... {w}это меня малость... {w}огорчило.")
        $ Obs.Say("th", "Постепенно после этого я уже начинал потихоньку терять к той интерес.")
        $ Obs.Say("th", "Но однажды, уже вдоль и поперёк пройдя игру, я решил перейти наконец к модам и скачал аддон к оригинальному сюжету под названием \"Мику-рут для оригинального сценария\".")
        $ Obs.Say("th", "В тот день мне уже начинало становиться интересно, как бы выглядел её рут, если бы тот был представлен в оригинале в том же виде, что и другие...")
        $ Obs.Say("th", "А не в качестве просто отдельного хоррор-рута, который не имеет ничего общего с основным сюжетом.")
        $ Obs.Say("th", "Мику была единственным персонажем в новелле, который ну никак не был раскрыт и представлен лишь в качестве отсылки. {w}И на первый взгляд о ней складывалось впечатление, что та лишь просто говорливая девочка, у которой на уме одна лишь музыка, и всё.")
        $ Obs.Say("th", "Но вот когда я прошёл наконец тот аддон, и у меня в голове наконец более-менее встало всё на свои места о представлении её характера... {w}или же каким он мог бы быть в оригинале...")
        $ Obs.Say("th", "...Меня всё больше и больше начинала та заинтересовывать. {w}И я начинал проходить уже другие модификации, посвящённые ей... {w}или же просто с присутствием и её рута.")
        $ Obs.Say("th", "И в конце концов, я постепенно стал уже микуфагом. {w}И кажется, с каждым днём всё больше и больше становлюсь таковым. {w}У меня уже даже кружка с её именем.")
        $ Obs.Hide.Image("prologue_dream", _with=dissolve2)
        $ Obs.Say("th", "Эх, Мику-Мику...")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "3", True)
        $ Obs.Return()

    label obs_prologue_room_items.check4:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Третий ведьмак...")
        $ Obs.Say("th", "Прям-таки игра года, переплюнувшая многие игры своим качеством и разнообразностью... {w}или же таковой была.")
        $ Obs.Say("th", "В настоящее время я уже не особо слежу за выходом новых игр... {w}Да и надо оно мне? {w}Всё равно кроме как в БЛ, ни во что не могу уже играть...")
        $ Obs.Say("th", "В любом случае, хоть я и не смог пока пройти ведьмака из-за своего, собственно, текущего состояния... {w}всё равно считаю эту игру одну из самых годных.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "4", True)
        $ Obs.Return()

    label obs_prologue_room_items.check5:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Ну-с, посмотрим, что у меня тут.")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(4, "Выдв. полка")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Куча всякого барахла, как всегда... {w}а вот нужного ничего нет.")
        $ Obs.Say("th", "Ищем дальше.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "5", True)
        $ Obs.Return()

    label obs_prologue_room_items.check6:
        if not obs_items_seen["6"]:
            $ Obs.Pause(0.7)
            $ Obs.Show.Screens()
            $ Obs.Say("th", "Хм... {w}Кажется, в последний раз я именно сюда спички положил. {w}Только бы они оказались на своём месте...")
            $ Obs.Hide.Screens()
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(1, "Выдв. полка", "matches")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Set.Quest("Найти спички.", True)
        if not Obs.InventoryIf("flashlight"):
            $ Obs.Say("th", "Так, спички есть, отлично. {w}Остался лишь фонарик.")
        else:
            $ Obs.Say("th", "Так, спички есть, отлично. {w}Вроде теперь всё взял?")
            $ Obs.Call.Label("obs_prologue_kitchen_items.memory")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "6", True)
        $ Obs.Return()

    label obs_prologue_room_items.check7:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Старая добрая вторая сонька...")
        $ Obs.Say("th", "Сколько же я на ней игр переиграл в своё время... {w}Даже и не сосчитать...")
        $ Obs.Say("th", "Resident Evil 4... {w}Silent Hill 4: The Room... {w}God of War II... {w}Grand Theft Auto: San Andreas... {w}Batman Begins...")
        $ Obs.Say("th", "Эх... {w}хорошие были времена... {w}Игры всегда мне помогали отвлечься от проблем... {w}расслабиться... {w}хорошо провести время...")
        $ Obs.Show.Image("prologue_dream", zorder=100, _with=dissolve2)
        $ Obs.Say("th", "Они были единственным, что меня хоть как-то могло порадовать в этой жизни... {w}хоть как-то помочь уйти от этой чёртовой депрессии... {w}Правда, лишь временно, но лучше хоть как-то, чем никак.")
        $ Obs.Say("th", "Но депрессия моя с годами всё больше и больше росла, и с ней становилось всё сложнее и сложнее справляться...")
        $ Obs.Say("th", "В один момент игры и вовсе перестали мне уже помогать... Просто-навсего не игралось уже в них...")
        $ Obs.Say("th", "Только запускал какую-то игру, как через какое-то время уже пропадала всякая мотивация продолжать её проходить...")
        $ Obs.Say("th", "Я переставал видеть смысл в чём-либо... {w}Всё начинало казаться каким-то{el} бессмысленным...")
        $ Obs.Say("th", "Но всё изменилось, когда я однажды сидя в интернете и думая чем себя занять, натолкнулся на видео с прохождением Бесконечного Лета... {w}От нечего делать я его решил запустить.")
        $ Obs.Say("th", "И с первых минут просмотра промелькнула какая-то искорка... {w}искорка, дающая понять, что ещё существует игра, которая способна вытянуть меня из этой непроглядной тьмы.")
        $ Obs.Say("th", "В тот же день я зарегистрировался в Steam и скачал сею шедевриальную новеллу, которую после только и делал, что целыми днями проходил, всё не прекращая удивляться, насколько эта игра шикарна как и сами моды к ней.")
        $ Obs.Say("th", "Ни в одной игре я не испытывал столько эмоций, сколько испытал в ней. {w}И за всё время, проведённом за ней и модами, я, казалось бы, уже успел целую жизнь прожить... {w}настолько буйные эмоции были испытаны.")
        $ Obs.Say("th", "Боюсь представить, что было бы со мной, если бы я так и не узнал об этой игре... {w}или же если бы её и вовсе не существовало...")
        $ Obs.Say("th", "Я бы, наверное, к этому времени уже{el} нет, лучше не думать об этом...")
        $ Obs.Hide.Image("prologue_dream", _with=dissolve2)
        $ Obs.Say("th", "Так, ладно, пора бы уже вещи искать, а то я опять слишком ушёл в свои мысли.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "7", True)
        $ Obs.Return()

    label obs_prologue_room_items.check8:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Может быть, еды какой прихватить с собой в дорогу? {w}Миха, конечно, скорей всего, и сам её возьмёт, но всё же лучше перестраховаться.")
        $ Obs.Hide.Screens()
        $ Obs.Pause(1.0)
        $ Obs.Play.Sound("obs_fridge")
        $ Obs.Pause(1.0)
        $ Obs.Show.ItemsMenu(4, "Холодильник")
        $ Obs.Play.Sound("obs_fridge")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Да... {w}с едой как-то бедно. {w}Надо будет завтра в магазин сходить за продуктами.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "8", True)
        $ Obs.Return()

    label obs_prologue_room_items.check9:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Старый-престарый домашний телефон... {w}много уже повидавший...")
        $ Obs.Say("th", "Сколько лет он уже тут лежит? {w}А я никак его не удосужусь выкинуть...")
        $ Obs.Say("th", "Тот, естественно, давно уже перестал работать. {w}Ну а я всё продолжаю его хранить...")
        $ Obs.Say("th", "Ну и пусть лежит тут дальше. {w}Всё равно тот никому не мешает, как бы.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "9", True)
        $ Obs.Return()

    label obs_prologue_room_items.check10:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Фонарик вроде как в этой коробке я обычно хранил. {w}Правда, уже не помню, куда его в последний раз засунул...")
        $ Obs.Say("th", "Но в любом случае, буду надеяться, что тот здесь.")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1.0)
        $ Obs.Show.ItemsMenu(4, "Коробка")
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "И как на зло, того здесь нету... {w}На кухне, может, он?")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "10", True)
        $ Obs.Return()

label obs_prologue_kitchen_items:

    label obs_prologue_kitchen_items.loop:
        $ Obs.Show.NormalScreens(False)
        $ Obs.Call.Screen("obs_prologue_kitchen_clicked")
        $ Obs.Return()

    label obs_prologue_kitchen_items.move:
        $ Obs.Front(obs_xoffset_ease(0, -500, 1.0))
        $ Obs.Pause(1.0)
        $ Obs.Play.Sound("obs_walk", end=1.5)
        $ Obs.Scene.Image("obs_gray2")
        $ Obs.Show.Image("obs_snow right", at=obs_alpha(0.7))
        $ Obs.Show.Image("bg obs_art_kitchen_gray")
        $ Obs.Show.Image("obs_art_kitchen_backpack_gray", at=obs_align(0.157, 1.0))
        $ Obs.With.Statement(pushleft)
        $ Obs.Front(obs_xoffset_ease(-500, 0, 1.0))
        $ Obs.Return()

    label obs_prologue_kitchen_items.check1:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Мику и её очаровательное пение, которое разжигает огонь в сердцах молодых пионеров. {w}Любите пение.")
        $ Obs.Say("th", "Припоминаю, купил этот плакат в каком-то магазине... {w}Тот очень даже хорошо вписался сюда.")
        $ Obs.Say("th", "Прям-таки сразу уют с ним чувствуется в помещении.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "11", True)
        $ Obs.Return()

    label obs_prologue_kitchen_items.check2:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Посмотрим, что здесь...")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(4, "Шкафчик")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Ожидаемый результат...")
        if not Obs.InventoryIf("matches") and not Obs.InventoryIf("flashlight"):
            $ Obs.Say("th", "Как всегда, положил куда-то эти вещи, где 2 часа буду их искать... {w}Пора бы мне уже научиться складывать всё в одном месте.")
        elif not Obs.InventoryIf("matches"):
            $ Obs.Say("th", "Как всегда, положил куда-то эти спички, где 2 часа буду их искать... {w}Пора бы мне уже научиться складывать всё в одном месте.")
        elif not Obs.InventoryIf("flashlight"):
            $ Obs.Say("th", "Как всегда, положил куда-то этот фонарик, где 2 часа буду его искать... {w}Пора бы мне уже научиться складывать всё в одном месте.")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "12", True)
        $ Obs.Return()

    label obs_prologue_kitchen_items.check3:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Так-так, посмотрим...")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(3, "Шкафчик", "knife", {"d":5, "h":7, "s":20, "e":["bleeding", 5]})
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Stop.Music(5)
        $ Obs.Set.Quest("Найти нож.", True)
        $ Obs.Say("th", "Кухонный, думаю, сгодится.")
        $ Obs.Say("th", "Ну, теперь точно всё. {w}Осталось только это всё в рюкзак сложить и переодеться.")
        $ Obs.Set.Quest("Взять рюкзак.", False)
        $ Obs.Hide.Screens()
        $ Obs.Return()

    label obs_prologue_kitchen_items.check4:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Так... {w}что здесь у меня полезного?")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(4, "Шкафчик")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Ни-{w}че-{w}го...")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "14", True)
        $ Obs.Return()

    label obs_prologue_kitchen_items.check5:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Начнём поиски...")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(4, "Шкафчик")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Ничего нужного...")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "15", True)
        $ Obs.Return()

    label obs_prologue_kitchen_items.check6:
        $ Obs.Pause(0.7)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Сейчас проверим здесь...")
        $ Obs.Hide.Screens()
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(1)
        $ Obs.Play.Sound("obs_cupboard")
        $ Obs.Pause(1)
        $ Obs.Show.ItemsMenu(2, "Шкафчик", "flashlight")
        $ Obs.Play.Sound("open_cupboard")
        $ Obs.Pause(0.5)
        $ Obs.Show.Screens()
        $ Obs.Set.Quest("Найти фонарик.", True)
        if not Obs.InventoryIf("matches"):
            $ Obs.Say("th", "Надо же... {w}вот и фонарик нашёлся. {w}Остались только спички.")
        else:
            $ Obs.Say("th", "Надо же... {w}вот и фонарик нашёлся. {w}Вроде теперь всё взял?")
            $ Obs.Call.Label("obs_prologue_kitchen_items.memory")
        $ Obs.Hide.Screens()
        $ Obs.GlobalDict("obs_items_seen", "16", True)
        $ Obs.Return()

    label obs_prologue_kitchen_items.memory:
        $ Obs.Say("...")
        $ Obs.Say("Я вдруг вспомнил, что Миха говорил мне взять ещё и нож.")
        $ Obs.Say("th", "Интересно, зачем ему он? {w}Он чего-то боится? {w}Или это просто подстраховка?")
        $ Obs.Say("th", "...")
        $ Obs.Say("th", "Ладно... {w}я всё же возьму нож, несмотря на то, что я не имею ни малейшего понятия, для чего он мог бы пригодиться там...")
        $ Obs.Say("th", "Если он знает весь лес... {w}то зачем, собственно, ему эти предметы?")
        $ Obs.Say("th", "...")
        $ Obs.Say("th", "В любом случае, ответ я получу {-} лишь спросив у него это сам.")
        $ Obs.Say("th", "Так-с, ножи да ложки у меня в шкафчике возле раковины.")
        $ Obs.Set.Quest("Найти нож.", False)
        $ Obs.Return(check=False)

    label obs_prologue_kitchen_items.end:
        $ Obs.Show.Item("easy")
        $ Obs.Hide.Image("obs_art_kitchen_backpack_gray", _with=dissolve)
        $ Obs.Set.Quest("Взять рюкзак.", True)
        $ Obs.Set.Quest("Поход с Михылычем.", "end")
        $ Obs.Pause(1.0)
        $ Obs.Show.Message("backpack")
        $ Obs.Pause(1.0)
        $ Obs.Set.Quest(None)
        $ Obs.Show.Screens()
        $ Obs.Say("th", "Теперь можно идти.")
        $ Obs.Jump.Label("obs_prologue_room_items_end")
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
