



label obs_introduction:
    $ Obs.Global("obs_game_menu", True)
    $ Obs.Set.Day("Вступление")
    $ Obs.Set.DayTime("rain")
    $ Obs.AutoSave("", False)
    $ Obs.Pause(2.5)
    $ Obs.Set.Volume(0.5, "ambience")
    $ Obs.Play.Ambience("obs_rain_outside", 7)
    $ Obs.Play.Sound("obs_thunder_strike")
    $ Obs.With.Statement(flash)
    $ Obs.Pause(1)
    $ Obs.Show.Text("Настоящее время", 80, 3, 3)
    $ Obs.Play.SoundLoop("obs_running_through_the_puddles", 7)
    $ Obs.Play.SoundLoop2("obs_head_heartbeat", 7)
    $ Obs.Play.Music("obs_norikoeru_beki_wa_satsugai_kyoufu", 5)
    $ Obs.Pause(2)
    $ Obs.Show.Screens(True)

    $ Obs.Say("Я бежал...")

    $ Obs.Hide.Screens(True)
    $ Obs.Scene.Image("bg obs_forest_running", at=obs_run_anim)
    $ Obs.Show.Image("obs_eff_hard_rain left")
    $ Obs.Show.Image("obs_smoke", at=obs_yoffset_ease(0, -300, 5.0))
    $ Obs.Master(obs_bg_zoom_e(1.0, 2.0, 5.0, y=0.45, yy=0.45), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("Всё бежал, не останавливаясь...")

    $ Obs.Hide.Screens(True)
    $ Obs.Hide.Image("black")
    $ Obs.Show.Image("bg obs_forest_running2", at=obs_bg_zoom_e)
    $ Obs.Show.Image("obs_smoke", at=obs_yoffset(0))
    $ Obs.Master(obs_bg_zoom_e(2.0, 2.0, 5.0, 0.3, 0.7, 0.6, 0.6), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("Изводя дух, но не теряя темпа...")

    $ Obs.Hide.Screens(True)
    $ Obs.Hide.Image("black")
    $ Obs.Show.Image("bg obs_forest_running3")
    $ Obs.Master(obs_bg_zoom_e(2.0, 2.0, 5.0, 0.5, 0.1), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("А они всё... {w}преследовали меня...")

    $ Obs.Hide.Screens(True)
    $ Obs.Hide.Image("black")
    $ Obs.Show.Image("bg obs_forest_running4")
    $ Obs.Master(obs_bg_zoom_e(1.0, 2.0, 5.0), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("Всё подступая и подступая...")
    $ Obs.Say("Ожидая, что я вот-вот свалюсь с ног...")
    $ Obs.Say("И попаду в их цепкие руки...")

    $ Obs.Hide.Screens(True)
    $ Obs.Hide.Image("black")
    $ Obs.Show.Image("bg obs_forest_running5", at=obs_run_anim)
    $ Obs.Master(obs_bg_zoom_e(1.0, 2.0, 5.0, y=0.45, yy=0.45), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("Но я не готов был сдаваться...")
    $ Obs.Say("И всё продолжал искать путь спасения...")
    $ Obs.Say("Спасения... {w}от них...")
    $ Obs.Say("Ведь я должен... {w}должен... {w}спастись...")

    $ Obs.Hide.Screens(True)
    $ Obs.Hide.Image("black")
    $ Obs.Show.Image("bg obs_forest_running6", at=obs_run_anim)
    $ Obs.Show.Image("obs_smoke", at=obs_yoffset_ease(0, -300, 5.0))
    $ Obs.Master(obs_bg_zoom_e(1.0, 2.0, 5.0, 0.2, 0.2, 0.35, 0.35), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("Дождь всё продолжал усиливаться...")
    $ Obs.Say("Из-за грязи становилось труднее и труднее бежать...")
    $ Obs.Say("Силы начинали постепенно покидать меня...")

    $ Obs.Hide.Screens(True)
    $ Obs.Hide.Image("black")
    $ Obs.Show.Image("bg obs_forest_running7", at=obs_run_anim)
    $ Obs.Show.Image("obs_smoke", at=obs_yoffset(0))
    $ Obs.Master(obs_bg_zoom_e(1.0, 2.0, 5.0, 0.2, 0.2, 1.0, 1.0), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("Но я держался... {w}держался из последних сил...")
    $ Obs.Say("Не должно ведь всё вот так закончиться... {w}просто не должно...")
    $ Obs.Say("Не мог же весь этот путь быть проделан зря...")
    $ Obs.Say("Ведь сейчас столько на кону...")
    $ Obs.Say("И я не должен это всё... {w}просто взять и... {w}потерять...")

    $ Obs.Hide.Screens(True)
    $ Obs.Hide.Image("black")
    $ Obs.Show.Image("bg obs_forest_running", at=obs_run_anim)
    $ Obs.Show.Image("obs_smoke", at=obs_yoffset_ease(0, -300, 5.0))
    $ Obs.Master(obs_bg_zoom_e(1.0, 2.0, 5.0, y=0.45, yy=0.45), _with=obs_flash)
    $ Obs.Pause(3)
    $ Obs.Show.Image("black", sound="obs_screamer10", _with=obs_flash)
    $ Obs.Show.Screens(True)

    $ Obs.Say("И только было я обнаружил наконец впереди себя укрытие...")

    $ Obs.Show.NotScreens(_with=obs_dissolve)
    $ Obs.Stop.SoundLoop(3)
    $ Obs.Stop.SoundLoop2(3)
    $ Obs.Stop.Ambience(3)
    $ Obs.Stop.Music(3)
    $ Obs.Show.NormalScreens(False)
    $ Obs.Pause(1)

    $ Obs.Say("Я увидел то, чего боялся увидеть больше всего на свете на данный момент...", _with=obs_dissolve8)
    $ Obs.Say("th", "Нет...", dis=True)
    $ Obs.Say("th", "Только...", dis=True)
    $ Obs.Say("th", "Не...", dis=True)
    $ Obs.Say("th", "Это...", dis=True)

    $ Obs.Show.NotScreens(_with=obs_dissolve)
    $ Obs.Show.Image("obs_forest_in_the_fog2_layer2", sound="obs_screamer7")
    $ Obs.Master(obs_bg_zoom_e(1.0, 3.0, 1.0, y=0.35, yy=0.35))
    $ Obs.Pause(0.5)
    $ Obs.Stop.Music(5)
    $ Obs.Scene.Image("black", _with=obs_dissolve4)
    $ Obs.Pause(3)
    $ Obs.Show.NormalScreens(_with=obs_dissolve)

    $ Obs.Say("th", "...А всё так хорошо начиналось...")

    $ Obs.Show.NotScreens(_with=obs_dissolve16)
    $ Obs.Pause(1)
    $ Obs.Show.Text("За некоторые дни до этого...", 80, 3, 3)
    $ Obs.Pause(2)
    $ Obs.Set.Volume(1.0, "ambience")
    $ Obs.Jump.Label("obs_prologue_main")
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
